name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: install pre-requisites
      run: |
        sudo apt update
        sudo apt install -y libboost1.65-all-dev
    - name: cmake
      run: |
        mkdir build
        cd build 
        cmake ..
    - name: build binary
      run: |
        cd build
        make
