name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: install pre-requisites
      run: |
        sudo apt update
        sudo apt install -y libboost1.65-all-dev build-essential gcc make cmake cmake-gui cmake-curses-gui libssl-dev doxygen graphviz
        cd thirdparty
        git clone -b v1.3.1 https://github.com/eclipse/paho.mqtt.c.git
        git clone -b v1.1 https://github.com/eclipse/paho.mqtt.cpp
        pushd paho.mqtt.c
        cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_ENABLE_TESTING=OFF
        sudo cmake --build build/ --target install
        sudo ldconfig
        popd
        cd paho.mqtt.cpp
        cmake -Bbuild -H.
        sudo cmake --build build/ --target install
        sudo ldconfig
    - name: cmake
      run: |
        mkdir build
        cd build 
        cmake ..
    - name: build binary
      run: |
        cd build
        make
